export const ADD_CONTENT = "ADD_CONTENT";
export const SET_CONTENTS = "SET_CONTENTS";
export const ADD_READING_HISTORY = "ADD_READING_HISTORY";
export const REMOVE_CONTENT = "REMOVE_CONTENT";
export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const SORT_BY_FIRST_UPLOAD = "SORT_BY_FIRST_UPLOAD";
export const SORT_BY_LAST_UPLOAD = "SORT_BY_LAST_UPLOAD";
